### Visual Studio Code Extension: REST Client, Huachao Mao.

### nice
POST http://localhost:8000/user/add 
content-type: application/json

{
    "email": "ocki.bagus.p@gmail.com",
    "password": "admin123",
    "name": "Ocki Bagus Pratama"
}

### (?)

POST http://localhost:8000/user/add 
Content-Type: application/x-www-form-urlencoded

{
    "email": "ocki.bagus.p@gmail.com",
    "password": "admin123",
    "name": "Ocki Bagus Pratama"
}